#!/usr/bin/env bash
# Generated by workflow-architect — review before running
# Kanban board for developer-pipeline-kanban
# Archetype: build-review-deploy

set -euo pipefail

BOARD_SLUG="developer-pipeline-kanban"
BOARD_NAME="Developer Pipeline Kanban"

echo "Creating kanban board: $BOARD_NAME ($BOARD_SLUG)"

# Create the board
hermes kanban boards create "$BOARD_SLUG" \
  --name "$BOARD_NAME" \
  --description "Generated by workflow-architect on 2026-05-29" \
  --switch

echo "Board created and switched to $BOARD_SLUG"
echo ""
echo "To add work, create a task for the Build phase:"
echo '  hermes kanban create "Build: <feature>" --skill developer-pipeline-kanban/build --priority 3'
echo ""
echo "Then chain Review and Deploy tasks:"
echo '  hermes kanban create "Review: <feature>" --parent <build-task-id> --skill developer-pipeline-kanban/review --priority 2'
echo '  hermes kanban create "Deploy: <feature>" --parent <review-task-id> --skill developer-pipeline-kanban/deploy --priority 1'
echo ""
echo "See kanban/task-blueprints.yaml for templates."
